### ISSUE TITLE
Retain history for a location?

### ISSUE THREAD

**Issue by junkyardsparkle** [pinballmap/pbm#1176] opened 2019-06-05 01:50 UTC
I created an account in order to remove a no-longer-there machine from a location, and was kind of sad to see that all traces of it having been there vanished from the visible record. It would be pretty great if past machines could still be displayed in a location record, or at least the last few. EDIT: It looks like the location itself doesn't immediately vanish from the map, at least.

**Comment by RyanTG** [comment] 2019-06-05 03:44
In the next version of the app, we show a log machines removed from places. It’ll only go back 30 days, though. And we plan to add this feature to the website, too. 

![3D7C4D7F-77AF-4283-A732-7A67E6B18D46](https://user-images.githubusercontent.com/632682/58928891-37ac3980-8709-11e9-99dc-3330ab8665db.png)

Generally, we don’t want to show people places that don’t have machines. But I understand that it would be neat to see what used to be at a place, though. 

And you’re right, the locations aren’t immediately deleted. But they are within a week.

**Comment by junkyardsparkle** [comment] 2019-06-05 04:18
Cool, and thanks for all of this. Has any consideration been given to retaining n previous machines, rather than (or combined with) a time limit? I'm also thinking that if previously active locations could be retained as an optionally searchable db, it might assist with rediscovery by intrepid explorers if they become active again in the future... but maybe I'm being overly optimistic there.

**Comment by RyanTG** [comment] 2022-04-18 16:20
Kind of a dupe of https://github.com/pinballmap/pbm/issues/1194

**Closed by RyanTG** 2022-04-18 16:20 UTC
