### ISSUE TITLE
Cost field

### ISSUE THREAD

**Issue by ggfevans** [pinballmap/pbm#1597] opened 2024-09-05 19:57 UTC
It would be great to have a field for each venue showing its cost and payment method. Some venues use tokens, while others accept credit cards. Clubs may require membership.

**Comment by RyanTG** [comment] 2024-09-05 19:59
Duplicate of https://github.com/pinballmap/pbm/issues/1584 (which I just re-opened in place of this).

Still not convinced if we need a field for this, though. It would be another dataset for users to maintain, and would likely be very duplicative of the "location description").

**Closed by RyanTG** 2024-09-05 19:59 UTC
